# Generated by Django 3.0.2 on 2020-05-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='client_ip',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
