# Generated by Django 3.0.2 on 2020-05-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_actions_client_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='actions',
        ),
    ]
