# Generated by Django 3.0.2 on 2020-04-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billingprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
