# Generated by Django 3.0.2 on 2020-04-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_product'),
        ('shop', '0005_auto_20200411_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='tags.Tag'),
        ),
    ]
