# Generated by Django 3.0.2 on 2020-04-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
