# Generated by Django 3.0.2 on 2020-04-09 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_item_item_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='user',
        ),
    ]
