# Generated by Django 3.0.2 on 2020-04-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Billingprofiles', '0002_auto_20200414_1729'),
        ('orders', '0003_auto_20200413_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billingprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Billingprofiles.billingProfile'),
        ),
    ]
